


import com.mysql.jdbc.exceptions.jdbc4.*;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author KawiYaa
 */
public class OrderFrame extends javax.swing.JFrame {

    /**
     * Creates new form OrderFrame
     */
    Connection conn = null;
    Statement stmt = null;
    ResultSet rs = null;
    
    public OrderFrame() {
        super("Order Content");
        initComponents();
        conn = DatabaseConnection.connection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelPizza = new javax.swing.JLabel();
        LablePasta = new javax.swing.JLabel();
        LabelBeverages = new javax.swing.JLabel();
        LableStarter = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CustomerIdTextBox = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        PizzaType = new javax.swing.JComboBox();
        Pasta1 = new javax.swing.JComboBox();
        Beverage1 = new javax.swing.JComboBox();
        Starter1 = new javax.swing.JComboBox();
        Error = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPizza.setBackground(new java.awt.Color(0, 0, 0));
        labelPizza.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelPizza.setForeground(new java.awt.Color(0, 0, 153));
        labelPizza.setText("Pizza Type");
        jPanel1.add(labelPizza, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        LablePasta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LablePasta.setForeground(new java.awt.Color(0, 0, 153));
        LablePasta.setText("Pasta ");
        jPanel1.add(LablePasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        LabelBeverages.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelBeverages.setForeground(new java.awt.Color(0, 0, 153));
        LabelBeverages.setText("Beverage");
        jPanel1.add(LabelBeverages, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 147, -1, -1));

        LableStarter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LableStarter.setForeground(new java.awt.Color(0, 0, 153));
        LableStarter.setText("Starter");
        jPanel1.add(LableStarter, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("Customer ID");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));
        jPanel1.add(CustomerIdTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 203, -1));

        AddButton.setBackground(new java.awt.Color(255, 51, 51));
        AddButton.setText("Add");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });
        jPanel1.add(AddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, -1));

        BackButton.setBackground(new java.awt.Color(153, 0, 0));
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        jPanel1.add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, -1, -1));

        PizzaType.setBackground(new java.awt.Color(0, 0, 153));
        PizzaType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Traditional Italiano", "Modern Magic" }));
        jPanel1.add(PizzaType, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 130, -1));

        Pasta1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cheese", "meatless", " ", " " }));
        jPanel1.add(Pasta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 100, -1));

        Beverage1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cocacola", "Pepsi", "Sprite", "Fanta" }));
        jPanel1.add(Beverage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 100, -1));

        Starter1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(Starter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 100, -1));

        Error.setBackground(new java.awt.Color(255, 51, 51));
        Error.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.add(Error, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 240, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background final.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-26, -6, 450, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(416, 396));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // TODO add your handling code here:
        try{
            try{
            stmt = conn.createStatement();
            String Pizza_Type=PizzaType.getSelectedItem().toString();
            String Pasta=Pasta1.getSelectedItem().toString();
            String Beverage=Beverage1.getSelectedItem().toString();
            String Starter=Starter1.getSelectedItem().toString();
            int Customer_ID = Integer.parseInt(CustomerIdTextBox.getText());
          
            String sql = "INSERT INTO orders(Pizza_Type, Pasta, Beverage, Starter, Customer_ID) VALUES('"+Pizza_Type+"', '"+Pasta+"', '"+Beverage+"', '"+Starter+"', '"+Customer_ID+"')";
            
            stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "customer "+Customer_ID+", Order Successfully Added");
            }catch( MySQLIntegrityConstraintViolationException e){
                Error.setText("This customer not Added");
            }
        }catch(HeadlessException | NumberFormatException | SQLException e) {
            Error.setText("Please Enter Correct Values");
        }
            
    }//GEN-LAST:event_AddButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
                setVisible(false);
                MenuFrame object = new MenuFrame();
                object.setVisible(true);       
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton BackButton;
    private javax.swing.JComboBox Beverage1;
    private javax.swing.JTextField CustomerIdTextBox;
    private javax.swing.JLabel Error;
    private javax.swing.JLabel LabelBeverages;
    private javax.swing.JLabel LablePasta;
    private javax.swing.JLabel LableStarter;
    private javax.swing.JComboBox Pasta1;
    private javax.swing.JComboBox PizzaType;
    private javax.swing.JComboBox Starter1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelPizza;
    // End of variables declaration//GEN-END:variables
}
